#server:
    #port: 46018
    #ssl:
    #    keyStore: /security/cacerts/keystore.jks
    #    keyStorePassword: changeit
    #    keyPassword: changeit

logging:
  level.root: ERROR
  level.com.dell.isg.smi: TRACE
  file: /var/log/dell/server-configuration-profile.log

spring:
   #application:
     #name: SERVER-CONFIG
   jackson:
     serialization-inclusion : non_null

nfs_script_file:
   script_name: nfs_tool.sh
   script_directory: /opt/dell/smi/scripts

#eureka:
  #client:
    #serviceUrl:
       #defaultZone: http://service-registry:8600/eureka/

